<?php
/**
 * Luxe
 * MostViewed module
 *
 * @category   design_default
 * @package    Luxe_MostViewed
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Luxe_MostViewed_Block_List_Toolbar
 */
?>

<?php if($this->getCollection()->getSize()): ?>
	<div style="width:100%; border-bottom:1px solid">
		<h3>Most viewed</h3>
	</div>
    
<?php endif ?>

