<?php echo $this->getToolbarHtml(); ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $baseconfig =  Mage::helper("jmbasetheme")->getactiveprofile();
   
    if ($baseconfig) : 
            $productlistimagewidth = $baseconfig["productlistimagewidth"];
            $productlistimageheight = $baseconfig["productlistimageheight"];
            $productgriddeslenght = $baseconfig["productgriddeslenght"];
            $productgridimageheight = $baseconfig["productgridimageheight"];
            $productgridimagewidth = $baseconfig["productgridimagewidth"];
            $showlabel = $baseconfig["showlabel"];
        else :
            $productlistimagewidth = 180;
            $productlistimageheight = 180;
            $productgriddeslenght = 0;
            $productgridimageheight = 180;
            $productgridimagewidth = 180;
            $showlabel = 0;
        endif;
   
    
?>

<?php
  $randomid = rand();  
?>


<div class="jm-product-list <?php echo $config['mode']; ?> clearfix">	
		<div class="page-title category-title">
			<h1>Best seller</h1>
		</div>
		<div class="listing-type-grid category-products">
			<?php $_collectionSize = $listall?$listall->count():0; ?>
			
			<?php $i = 0;
				$width = 100;
				// -- added by Duchh 15/12/2009
				$thumbnailw = $config['width'];
				$thumbnailh = $config['height'];
				$numberchar = $config['max'];

				if ($config['perrow']) $width = 100/$config['perrow'];
				$width = "style=\"width:{$width}%;\"";    
        $return = false;                
			?>							
			<?php if($_collectionSize){?>
				<ul class="products-grid products-grid-special" id="productsgrid<?php echo $randomid; ?>">
				<?php foreach ($listall->getItems() as $_product){ 
						$_rowCount = ceil($_collectionSize/$config['perrow']);
						if ($i%$config['perrow']==0) : $j++; endif;
						$i++;
						$product = Mage::getModel('catalog/product')->load($_product->getId());
						$attribute = $product->getResource()->getAttribute('label');
						if(is_object($attribute)){
						 
						    $_options= $attribute->getSource()->getAllOptions(true, true);
							foreach($_options as $option){
								  if ($option['value'] == $product->getData("label")){
									$class =  $option['label'];
								  }
							 }		   
							 $attdefaultvalue = $attribute->getDefaultValue();
							 $attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getlabel();
							 $attributeValueName = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('label');
								 if(strlen($attributeValue) &&  ($attdefaultvalue !== $attributeValue)) { 
									 $labeltype = $class;   
									 $labelname = $attributeValueName;     
									 } 
									 else {
									 $labeltype = "";
							 } 
						}
				?> 
						<li class="item <?php if ($j==$_rowCount) : echo "item-row-last"; endif; ?> <?php if(($i-1)%$config['perrow']==0): ?> first<?php elseif($i%$config['perrow']==0): ?> last<?php endif; ?>" <?php echo $width;?>>
							<div class="inner">
							<div class="product-image">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($productgridimagewidth,$productgridimageheight); ?>" width="<?php echo $productgridimagewidth;  ?>" height="<?php echo $productgridimageheight;  ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							</div>
							<div class="product-rating-review">
								<?php echo $this->getReviewsSummaryHtml($_product, true, true)?>
								<?php if ($labeltype && $showlabel): ?>
									<span class="<?php echo $labeltype; ?>-label label"><?php echo $labelname;	?></span>		
								<?php endif; ?>
							</div>
							<div class="product-information">
								<h5>
									<a title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">										
									<?php 
										if (strlen($_product->getName()) > 30) :
											echo strip_tags(substr($_product->getName(), 0, 20)).'...';
										else : 
											echo $_product->getName();
										endif;
									?>
									</a>
								</h5>
								<?php echo $this->getPriceHtml($_product,true, '_jmproduct_' . rand()) ?>
							 </div>
						</div>
						</li>					
				<?php }?>		
				</ul>
				<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
			<?php }?>	
		</div>
</div>